name: interface_test
description: Test package
publish_to: none

environment:
  sdk: ^3.5.0
  flutter: ">=3.27.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.10.5
  test: ^1.29.0
  genuis:
    path: ../../
