name: genuis
description: Code generation for theme classes based on files from the assets folder and its structure.
version: 0.1.1
repository: https://github.com/vaniapril/genuis
issue_tracker: https://github.com/vaniapril/genuis/issues

environment:
  sdk: ^3.8.0

dependencies:
  build: ^4.0.0
  source_gen: ^4.0.0
  yaml: ^3.1.3
  path: ^1.9.1
  xml: ^6.6.1
  dart_style: ^3.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

platforms:
  linux:
  windows:
  macos:

topics:
 - theme
 - theme-extension
 - assets
 - codegen
 - build-runner
