name: themes_test
description: Test package
publish_to: none

environment:
  sdk: ^3.10.8
  flutter: ">=3.38.9"

dependencies:
  flutter:
    sdk: flutter
  flutter_inset_shadow: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.10.5
  test: ^1.29.0
  genuis:
    path: ../../
